name: daily-roundup
on:
  schedule:
    - cron: "0 9 * * *"  # Runs every day at 9am UTC
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
      - name: Commit new post
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add .
          git commit -m "chore: publish roundup" || echo "nothing to commit"
          git push